/**
 * Database type definitions for Supabase
 * This would normally be generated by Supabase CLI
 */

export interface Database {
  public: {
    Tables: {
      audit_log: {
        Row: {
          id: number;
          created_at: string;
          actor_user_id: string | null;
          actor_role: string | null;
          action: string;
          entity: string | null;
          entity_id: string | null;
          ip: string | null;
          user_agent: string | null;
          metadata: any;
        };
        Insert: {
          id?: number;
          created_at?: string;
          actor_user_id?: string | null;
          actor_role?: string | null;
          action: string;
          entity?: string | null;
          entity_id?: string | null;
          ip?: string | null;
          user_agent?: string | null;
          metadata?: any;
        };
        Update: {
          id?: number;
          created_at?: string;
          actor_user_id?: string | null;
          actor_role?: string | null;
          action?: string;
          entity?: string | null;
          entity_id?: string | null;
          ip?: string | null;
          user_agent?: string | null;
          metadata?: any;
        };
      };
      app_rate_limits: {
        Row: {
          key: string;
          bucket: number;
          hits: number;
          reset_at: string;
        };
        Insert: {
          key: string;
          bucket: number;
          hits?: number;
          reset_at: string;
        };
        Update: {
          key?: string;
          bucket?: number;
          hits?: number;
          reset_at?: string;
        };
      };
    };
    Views: {
      app_monitor_table_sizes: {
        Row: {
          schema: string;
          table: string;
          total_size: string;
          total_bytes: number;
          heap_size: string;
          index_size: string;
          approx_rows: number;
        };
      };
      app_monitor_connections: {
        Row: {
          state: string;
          connections: number;
        };
      };
    };
    Functions: {
      rate_limit_hit: {
        Args: {
          p_key: string;
          p_limit: number;
          p_window_seconds: number;
        };
        Returns: {
          ok: boolean;
          remaining: number;
          reset_at: string;
        }[];
      };
    };
    Enums: {
      // Add any enums here
    };
  };
}
